import { useMemo, useState } from "react";
import { MapPanel } from "../MapPanel";
import type { VectorCollection } from "../analysis/model";
import type { ModuleId } from "../step2/model";
import type { DiagnosticRequest } from "../online/client";
import { buildPythonPackage } from "./archive";
import { bboxBoundary, climateRequests, defaultJob, METRICS, MODELS, PREP_MODULES, validateBoundary, validateJob, type Job } from "./config";
import "./styles.css";

const BASE=import.meta.env.BASE_URL;
const months=["January","February","March","April","May","June","July","August","September","October","November","December"];
function Years({title,value,onChange,min,max}:{title:string;value:[number,number];onChange:(v:[number,number])=>void;min:number;max:number}) {
  return <fieldset className="prep-years"><legend>{title}</legend><label>From<input type="number" aria-label={`${title} start year`} min={min} max={max} value={value[0]} onChange={e=>onChange([Number(e.target.value),value[1]])}/></label><span>→</span><label>To<input type="number" aria-label={`${title} end year`} min={min} max={max} value={value[1]} onChange={e=>onChange([value[0],Number(e.target.value)])}/></label></fieldset>;
}
function toggle<T>(values:T[],item:T):T[]{return values.includes(item)?values.filter(v=>v!==item):[...values,item];}

type OnlineSetup = { onSubmit:(request:DiagnosticRequest)=>Promise<void>; enabledModules:ModuleId[]; maxClimateRequests:number };
export function PreparationWizard({ganjam,online}:{ganjam:VectorCollection|null;online?:OnlineSetup}) {
  const [open,setOpen]=useState(!!online),[step,setStep]=useState(0),[job,setJob]=useState<Job>(()=>{
    const value=defaultJob();
    return online?{...value,maxDownloadGB:10,climate:{...value.climate,models:["ACCESS-CM2"],scenarios:["ssp245"]}}:value;
  });
  const [landModules,setLandModules]=useState<("lulc"|"fragmentation")[]>([]);
  const [land,setLand]=useState<NonNullable<DiagnosticRequest["land_cover"]>>({resolution:50,edge_width_m:50,include_mangroves:true,count_boundary_as_edge:false});
  const [region,setRegion]=useState("ganjam"),[custom,setCustom]=useState<VectorCollection|null>(null),[filename,setFilename]=useState("");
  const [bounds,setBounds]=useState([85.75,20.15,85.95,20.35]);
  const [os,setOs]=useState("windows"),[account,setAccount]=useState(false),[busy,setBusy]=useState(false),[status,setStatus]=useState(""),[error,setError]=useState<string|null>(null);
  const boundary=useMemo(()=>{
    try {return region==="ganjam"?ganjam:region==="upload"?custom:bboxBoundary(...bounds as [number,number,number,number]);}catch{return null;}
  },[region,ganjam,custom,bounds]);
  const area=useMemo(()=>{try{return boundary?validateBoundary(boundary).areaKm2:null;}catch{return null;}},[boundary]);
  const nasa=job.modules.includes("groundwater")||job.modules.includes("drought");
  const patch=<K extends keyof Job>(key:K,value:Job[K])=>{setJob(j=>({...j,[key]:value}));setStatus("");setError(null);};
  function advance(next:number){
    try{
      if(next>0){if(!boundary)throw new Error("Choose a valid study-area boundary.");validateBoundary(boundary);if(!job.name.trim())throw new Error("Enter a study-area name.");}
      if(next>1){
        if(online&&job.modules.length===0&&landModules.length===0)throw new Error("Select at least one diagnostic.");
        validateJob(online&&!job.modules.length?{...job,modules:["flood"]}:job,false);
        if(online){
          if(new TextEncoder().encode(JSON.stringify(boundary)).length>190_000)throw new Error("Simplify the boundary to under 190 KB for online submission.");
          if(job.modules.includes("climate")&&climateRequests(job)>online.maxClimateRequests)throw new Error(`The server allows ${online.maxClimateRequests} annual climate subset requests per task. Keep your intended periods and split models or indices across tasks.`);
          if(landModules.length&&land.edge_width_m<land.resolution)throw new Error("Forest edge width must be at least one analysis cell.");
        }
      }
      setStep(next);setError(null);setStatus("");
    }catch(e){setError((e as Error).message);}
  }
  async function download(){
    setBusy(true);setError(null);setStatus("Preparing your configured Python package…");
    try{
      if(!boundary)throw new Error("Choose a study-area boundary.");
      if(nasa&&!account)throw new Error("Confirm that you can use your own NASA Earthdata account, or deselect the NASA-login modules.");
      const bytes=await buildPythonPackage(job,boundary,BASE);
      const url=URL.createObjectURL(new Blob([bytes.buffer],{type:"application/zip"}));
      const a=document.createElement("a");a.href=url;a.download="nbs-local-preparation.zip";a.click();setTimeout(()=>URL.revokeObjectURL(url),30_000);
      setStatus("Download ready. Extract the ZIP, install Python 3.12 if needed, and open the launcher. When it finishes, import results.zip below.");
    }catch(e){setError((e as Error).message);setStatus("");}finally{setBusy(false);}
  }
  async function submitOnline(){
    if(!online||!boundary)return;
    setBusy(true);setError(null);setStatus("Submitting your calculation…");
    try{await online.onSubmit({mode:"custom",name:job.name,modules:[...landModules,...job.modules],boundary,config:job,land_cover:land});setStatus("Task submitted. Follow its progress and results below; you can close this page.");}
    catch(e){setError((e as Error).message);setStatus("");}finally{setBusy(false);}
  }
  return <section id={online?"online-preparation":"local-preparation"} className="card prep-card">
    <div className="section-heading"><div><p className="step-number">{online?"YOUR REGION · SERVER COMPUTATION":"YOUR REGION · YOUR COMPUTER"}</p><h2>{online?"Configure your online analysis":"Prepare data for another study area"}</h2><p className="section-copy">{online?"Choose a boundary, data periods and diagnostics. The server downloads available source data and prepares your results.":"Choose your options here. Download a ready-configured Python package, run it on your computer, then bring the results back to this map."}</p></div>{!online&&<button className="quiet-button" aria-expanded={open} onClick={()=>setOpen(v=>!v)}>{open?"Close setup":"Create Python package →"}</button>}</div>
    {!open&&<div className="prep-flow" aria-label="Local preparation workflow"><span>1 · Choose</span><span>2 · Download & run</span><span>3 · Import results</span><a href="#import-local-results">Already have results? Import ↓</a></div>}
    {open&&<div className="prep-body">
      <nav className="prep-steps" aria-label="Preparation steps">{["Study area","Diagnostics",online?"Review & submit":"Download & run"].map((name,i)=><button key={name} aria-current={step===i?"step":undefined} disabled={busy} onClick={()=>advance(i)}><span>{i+1}</span>{name}</button>)}</nav>
      {step===0&&<div className="prep-region-grid"><div>
        <label className="prep-field">Study-area name<input value={job.name} maxLength={120} onChange={e=>patch("name",e.target.value)}/></label>
        <label className="prep-field">Boundary source<select value={region} onChange={e=>{setRegion(e.target.value);setError(null);patch("name",e.target.value==="ganjam"?"Ganjam District, Odisha":e.target.value==="rectangle"?"My study area":"");}}><option value="ganjam">Use Ganjam example boundary</option><option value="upload">Upload a GeoJSON boundary</option><option value="rectangle">Enter a rectangular area</option></select></label>
        {region==="upload"&&<><label className="prep-field">Boundary GeoJSON<input type="file" accept=".geojson,.json" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;try{if(f.size>(online?190_000:10_000_000))throw new Error(online?"Simplify the boundary to under 190 KB for online submission.":"Boundary limit is 10 MB.");const a=validateBoundary(JSON.parse(await f.text()));setCustom(a.boundary);setFilename(f.name);if(!job.name.trim())patch("name",f.name.replace(/\.(geojson|json)$/i,""));setError(null);}catch(err){setCustom(null);setError((err as Error).message);}e.target.value="";}}/></label><p className="field-help">{filename||(online?"Use a WGS84 polygon or multipolygon under 190 KB. The server checks enclosing-rectangle and module limits.":"Use a WGS84 polygon or multipolygon. Up to 10 MB and 50,000 km².")}</p></>}
        {region==="rectangle"&&<><div className="prep-bounds">{["West longitude","South latitude","East longitude","North latitude"].map((label,i)=><label key={label} className="prep-field">{label}<input type="number" step="0.01" min={i%2?-85:-180} max={i%2?85:180} value={bounds[i]} onChange={e=>setBounds(v=>v.map((n,j)=>j===i?Number(e.target.value):n))}/></label>)}</div><button className="text-button" onClick={()=>{setBounds([85.75,20.15,85.95,20.35]);patch("name","Bhubaneswar test area");}}>Use small Bhubaneswar test area</button><p className="field-help">A rectangle is useful for trying the workflow. Upload an administrative boundary for a district assessment.</p></>}
        <p className="prep-callout">{area!==null?`${area.toLocaleString("en",{maximumFractionDigits:1})} km² selected. `:"Select a valid boundary to see its area. "}Start with a small region. Larger areas need more memory and time; some module grids have stricter limits.</p>
      </div><div className="prep-map"><MapPanel aoi={boundary} label={job.name||"Boundary preview"} loading={region==="ganjam"&&!ganjam} error={null}/><p>{online?"Boundary preview · 20,000 km² maximum enclosing rectangle; 2,000 km² for new land-cover and forest tasks. Simplified boundaries must be under 190 KB.":"Boundary preview · your current analysis remains unchanged until you import results."}</p></div></div>}
      {step===1&&<div>
        <p className="section-copy">{online?"Choose the diagnostics to calculate. Source accounts are configured by the administrator; unavailable sources stay disabled until verified.":"Start with Flood and Land degradation for a smaller download. The two land-cover modules already accept your own GeoTIFFs in the analysis controls."}</p>
        <div className="prep-module-options">{online&&(["lulc","fragmentation"] as const).map(id=><label key={id} className={landModules.includes(id)?"selected":""}><input type="checkbox" checked={landModules.includes(id)} onChange={()=>setLandModules(m=>toggle(m,id))}/><span><strong>{id==="lulc"?"Land-cover change":"Forest fragmentation"}</strong><small>ESA WorldCover · 2020 and 2021</small><em>Server downloads and analyses public land-cover maps.</em></span></label>)}{PREP_MODULES.map(m=><label key={m.id} className={job.modules.includes(m.id)?"selected":""}><input type="checkbox" disabled={!!online&&!online.enabledModules.includes(m.id)} checked={job.modules.includes(m.id)} onChange={()=>patch("modules",toggle(job.modules,m.id))}/><span><strong>{m.title}</strong><small>{m.source}</small><em>{online&&!online.enabledModules.includes(m.id)?"Awaiting administrator setup and source verification.":online&&m.id==="groundwater"?"Server downloads and analyses regional daily data":online&&m.id==="drought"?"Server Earthdata account · large source downloads":m.note}</em></span></label>)}</div>
        {online&&landModules.length>0&&<fieldset className="prep-options"><legend>Land cover & forest structure</legend><p>Compare WorldCover 2020 v100 and 2021 v200. The map algorithms differ, so a mapped difference is not proof of real land-cover change.</p><div className="prep-bounds"><label className="prep-field">Analysis cell size<select value={land.resolution} onChange={e=>{const resolution=Number(e.target.value) as 30|50|100;setLand(v=>({...v,resolution,edge_width_m:Math.max(resolution,v.edge_width_m)}));}}>{[30,50,100].map(r=><option key={r} value={r}>{r} m</option>)}</select></label><label className="prep-field">Forest edge width (m)<input type="number" min={land.resolution} max={1000} value={land.edge_width_m} onChange={e=>setLand(v=>({...v,edge_width_m:Number(e.target.value)}))}/></label></div><div className="checkbox-list"><label><input type="checkbox" checked={land.include_mangroves} onChange={e=>setLand(v=>({...v,include_mangroves:e.target.checked}))}/>Include mangroves as forest</label><label><input type="checkbox" checked={land.count_boundary_as_edge} onChange={e=>setLand(v=>({...v,count_boundary_as_edge:e.target.checked}))}/>Count the study-area boundary as a forest edge</label></div><p>Tree cover is forest for this screening. Maximum two million analysis cells; use a small region first.</p></fieldset>}
        {job.modules.includes("flood")&&<fieldset className="prep-options"><legend>River flood hazard</legend><p>Choose return periods. A 100-year event has a 1% annual exceedance probability under the model assumptions.</p><div className="checkbox-list inline">{[10,100,500].map(p=><label key={p}><input type="checkbox" checked={job.flood.returnPeriods.includes(p)} onChange={()=>patch("flood",{returnPeriods:toggle(job.flood.returnPeriods,p).sort((a,b)=>a-b)})}/>{p}-year</label>)}</div></fieldset>}
        {job.modules.includes("degradation")&&<div className="prep-callout"><strong>Land degradation uses the publisher's fixed periods.</strong><p>2000–2015 baseline and the 2023 assessment. Productivity uses 2001–2015 / 2008–2023; land cover and soil carbon use 2000–2015 / 2015–2022. Years cannot be changed for this published product.</p></div>}
        {job.modules.includes("groundwater")&&<fieldset className="prep-options"><legend>Groundwater periods</legend><div className="prep-periods"><Years title="Groundwater baseline" value={job.groundwater.baseline} min={2003} max={2025} onChange={v=>patch("groundwater",{...job.groundwater,baseline:v})}/><Years title="Groundwater monitoring" value={job.groundwater.monitoring} min={2003} max={2025} onChange={v=>patch("groundwater",{...job.groundwater,monitoring:v})}/></div><p>Only regional daily groundwater data is downloaded. Long periods take time; January 2003 is unavailable. Results describe storage, not well depth. Use a long record for trend interpretation.</p></fieldset>}
        {job.modules.includes("climate")&&<fieldset className="prep-options"><legend>Climate projections</legend><div className="prep-periods"><Years title="Climate baseline" value={job.climate.baseline} min={1950} max={2020} onChange={v=>patch("climate",{...job.climate,baseline:v})}/><Years title="Climate future" value={job.climate.future} min={2021} max={2100} onChange={v=>patch("climate",{...job.climate,future:v})}/></div><p>Prefer 30-year periods for climate comparisons. Short periods are useful for checking the download workflow.</p>
          <fieldset><legend>Models</legend><div className="checkbox-list inline">{MODELS.map(m=><label key={m}><input type="checkbox" checked={job.climate.models.includes(m)} onChange={()=>patch("climate",{...job.climate,models:toggle(job.climate.models,m)})}/>{m}</label>)}</div></fieldset>
          <fieldset><legend>Scenarios</legend><div className="checkbox-list inline">{[["ssp245","SSP2-4.5 · intermediate emissions"],["ssp585","SSP5-8.5 · very high emissions"]].map(([v,label])=><label key={v}><input type="checkbox" checked={job.climate.scenarios.includes(v)} onChange={()=>patch("climate",{...job.climate,scenarios:toggle(job.climate.scenarios,v)})}/>{label}</label>)}</div></fieldset>
          <fieldset><legend>Indices</legend><div className="checkbox-list inline">{(Object.keys(METRICS) as (keyof typeof METRICS)[]).map(m=><label key={m}><input type="checkbox" checked={job.climate.metrics.includes(m)} onChange={()=>patch("climate",{...job.climate,metrics:toggle(job.climate.metrics,m)})}/>{METRICS[m]}</label>)}</div></fieldset>
          <details><summary>Temperature and rainfall thresholds</summary><div className="prep-bounds">{([["hot","Hot days above (°C)"],["warm","Warm nights above (°C)"],["rain","Heavy-rain days at least (mm/day)"],["dry","Dry days below (mm/day)"]] as const).map(([key,label])=><label className="prep-field" key={key}>{label}<input type="number" step="0.1" value={job.climate.thresholds[key]} onChange={e=>patch("climate",{...job.climate,thresholds:{...job.climate.thresholds,[key]:Number(e.target.value)}})}/></label>)}</div></details><p className="prep-callout">About {climateRequests(job).toLocaleString("en")} daily-file subset requests with these selections. Processing may take hours; completed requests are cached.</p>
        </fieldset>}
        {job.modules.includes("drought")&&<fieldset className="prep-options"><legend>Seasonal vegetation health</legend><p>This calculates MODIS VHI, a vegetation-stress screening indicator. It does not reproduce FAO ASIS. Choose growing months appropriate to the study area.</p><div className="prep-periods"><Years title="VHI reference" value={job.drought.reference} min={2001} max={2024} onChange={v=>patch("drought",{...job.drought,reference:v})}/><Years title="VHI comparison" value={job.drought.compare} min={job.drought.reference[0]} max={job.drought.reference[1]} onChange={v=>patch("drought",{...job.drought,compare:v})}/></div>
          <label className="prep-field">Number of growing seasons<select value={job.drought.seasons.length} onChange={e=>patch("drought",{...job.drought,seasons:Number(e.target.value)===1?[job.drought.seasons[0]]:[job.drought.seasons[0],{name:"Season 2",start:11,end:3}]})}><option value={1}>One season</option><option value={2}>Two seasons</option></select></label>
          {job.drought.seasons.map((s,i)=><div key={i} className="prep-season"><label className="prep-field">Season {i+1} name<input value={s.name} maxLength={50} onChange={e=>patch("drought",{...job.drought,seasons:job.drought.seasons.map((v,j)=>j===i?{...v,name:e.target.value}:v)})}/></label>{(["start","end"] as const).map(k=><label className="prep-field" key={k}>{k==="start"?"First month":"Last month"}<select value={s[k]} onChange={e=>patch("drought",{...job.drought,seasons:job.drought.seasons.map((v,j)=>j===i?{...v,[k]:Number(e.target.value)}:v)})}>{months.map((name,m)=><option key={name} value={m+1}>{name}</option>)}</select></label>)}</div>)}<p>Seasons may cross New Year and are labelled by their starting year. They must not overlap. At least 15 reference years must have valid observations.</p>
        </fieldset>}
        {(job.modules.includes("drought")||job.modules.includes("degradation"))&&<label className="prep-field">Area used for statistics<select value={job.landMask} onChange={e=>patch("landMask",e.target.value as Job["landMask"])}><option value="worldcover2021">WorldCover 2021 · crop area for VHI, non-water area for degradation</option><option value="all-land">Entire boundary · no crop or water mask</option></select><small>The fixed 2021 map does not establish historical cropping. Full-boundary mode must not be read as crop-only or land-only statistics.</small></label>}
      </div>}
      {step===2&&online?<div className="prep-review-grid"><div><h3>Review your task</h3><dl className="prep-summary"><dt>Study area</dt><dd>{job.name} · {area?.toLocaleString("en",{maximumFractionDigits:1})} km²</dd><dt>Diagnostics</dt><dd>{[...landModules.map(id=>id==="lulc"?"Land-cover change":"Forest fragmentation"),...PREP_MODULES.filter(m=>job.modules.includes(m.id)).map(m=>m.title)].join(", ")}</dd><dt>Calculation</dt><dd>Platform server · continue using your browser or return later</dd><dt>Results</dt><dd>Interactive maps, statistics, GeoTIFFs, CSV tables and a complete result ZIP</dd></dl></div><div className="prep-run-guide"><h3>Ready to calculate</h3><p>Your boundary and settings will be sent to the compute service. Tasks run in a queue; completed results stay available in your task history.</p>{job.modules.includes("climate")&&<p>{climateRequests(job)} annual climate subset requests. Long climate periods may take hours.</p>}<p>This server allows 10 GB of managed downloads and four hours per task. A source outage or limit may leave partial results; the result page identifies which diagnostics completed.</p><button className="run-button" disabled={busy} onClick={()=>void submitOnline()}>{busy?"Submitting…":"Submit calculation"}</button></div></div>:step===2&&<div className="prep-review-grid"><div>
        <h3>Your package</h3><dl className="prep-summary"><dt>Study area</dt><dd>{job.name} · {area?.toLocaleString("en",{maximumFractionDigits:1})} km²</dd><dt>Diagnostics</dt><dd>{PREP_MODULES.filter(m=>job.modules.includes(m.id)).map(m=>m.title).join(", ")}</dd><dt>Calculation</dt><dd>Your computer · Python · no platform server or Earth Engine project</dd><dt>Results</dt><dd>GeoTIFF layers, statistics, source manifest and results.zip for this website</dd></dl>
        {nasa&&<div className="prep-callout"><strong>NASA Earthdata login needed</strong><p>Create a free account at <a href="https://urs.earthdata.nasa.gov/" target="_blank" rel="noreferrer">NASA Earthdata</a>. The local script asks you to sign in. Some datasets also require accepting their data-use terms. Long MODIS periods can require tens of GB or more. Groundwater uses smaller regional subsets, but long periods still need many daily requests.</p><label><input type="checkbox" checked={account} onChange={e=>setAccount(e.target.checked)}/>I can use my own Earthdata account when the script asks.</label></div>}
        <details><summary>Download limit and files</summary><label className="prep-field">Managed-download limit per run (GB)<input type="number" min={.1} max={100} step={1} value={job.maxDownloadGB} onChange={e=>patch("maxDownloadGB",Number(e.target.value))}/></label><p>Limits direct downloads and NASA files. Raster range reads and dependency installation are excluded, so this is not a total network or disk cap. Completed requests and calculations are reused when you run the same folder again.</p><p>The ZIP includes run.py, launchers, requirements, your configuration, boundary and English instructions. No account credentials are included.</p></details>
      </div><div className="prep-run-guide"><h3>Run it in three steps</h3><label className="prep-field">Your computer<select value={os} onChange={e=>setOs(e.target.value)}><option value="windows">Windows</option><option value="macos">macOS</option><option value="linux">Linux / advanced</option></select></label><ol><li>Install <a href="https://www.python.org/downloads/" target="_blank" rel="noreferrer">Python 3.12</a> once. {os==="windows"?"Choose “Add Python to PATH”.":"Use the installer for your computer."}</li><li>Extract the ZIP. {os==="windows"?"Double-click Start Windows.bat.":os==="macos"?"Open Start macOS.command. The README gives a Terminal alternative if macOS blocks it.":"Run python3 run.py from the extracted folder."} The first run installs the required libraries.</li><li>Leave the terminal open. When it finishes, import <strong>results.zip</strong> below.</li></ol><p>Recommended: Windows 10/11 x64 or macOS 14+ Apple Silicon. Other systems need compatible Python libraries. The README explains interrupted downloads and incomplete modules.</p><button className="run-button" disabled={busy||(nasa&&!account)} onClick={()=>void download()}>{busy?"Preparing package…":"Download Python package ↓"}</button></div></div>}
      {error&&<p role="alert" className="error-box">{error}</p>}{status&&<p role="status" className="prep-callout">{status}</p>}
      <div className="prep-bottom"><span>{online?"Your study-area boundary and choices are sent to the server when you submit.":<>All setup choices stay in this browser until you download the package. <a href={`${BASE}local-preparation.en.md`} download>Full English guide ↓</a></>}</span><div>{step>0&&<button disabled={busy} className="quiet-button" onClick={()=>advance(step-1)}>← Back</button>}{step<2&&<button className="run-button" onClick={()=>advance(step+1)}>Continue →</button>}</div></div>
    </div>}
  </section>;
}
