import type { Dispatch, SetStateAction } from "react";
import type { DiagnosticRequest } from "./client";
import { climateRequests, METRICS, MODELS, type Job } from "../preparation/config";
const months=["January","February","March","April","May","June","July","August","September","October","November","December"];
function Years({title,value,onChange,min,max}:{title:string;value:[number,number];onChange:(v:[number,number])=>void;min:number;max:number}) {
  return <fieldset className="prep-years"><legend>{title}</legend><label>From<input type="number" aria-label={`${title} start year`} min={min} max={max} value={value[0]} onChange={e=>onChange([Number(e.target.value),value[1]])}/></label><span>→</span><label>To<input type="number" aria-label={`${title} end year`} min={min} max={max} value={value[1]} onChange={e=>onChange([value[0],Number(e.target.value)])}/></label></fieldset>;
}
function toggle<T>(values:T[],item:T):T[]{return values.includes(item)?values.filter(v=>v!==item):[...values,item];}

export function DiagnosticOptions({job,patch,land,landModules,setLand}:{job:Job;patch:<K extends keyof Job>(key:K,value:Job[K])=>void;land:NonNullable<DiagnosticRequest["land_cover"]>;landModules:("lulc"|"fragmentation")[];setLand:Dispatch<SetStateAction<NonNullable<DiagnosticRequest["land_cover"]>>>}){return <div className="analysis-options">        {landModules.length>0&&<fieldset className="prep-options"><legend>Land cover & forest structure</legend><p>Compare WorldCover 2020 v100 and 2021 v200. The map algorithms differ, so a mapped difference is not proof of real land-cover change.</p><div className="prep-bounds"><label className="prep-field">Analysis cell size<select value={land.resolution} onChange={e=>{const resolution=Number(e.target.value) as 30|50|100;setLand(v=>({...v,resolution,edge_width_m:Math.max(resolution,v.edge_width_m)}));}}>{[30,50,100].map(r=><option key={r} value={r}>{r} m</option>)}</select></label><label className="prep-field">Forest edge width (m)<input type="number" min={land.resolution} max={1000} value={land.edge_width_m} onChange={e=>setLand(v=>({...v,edge_width_m:Number(e.target.value)}))}/></label></div><div className="checkbox-list"><label><input type="checkbox" checked={land.include_mangroves} onChange={e=>setLand(v=>({...v,include_mangroves:e.target.checked}))}/>Include mangroves as forest</label><label><input type="checkbox" checked={land.count_boundary_as_edge} onChange={e=>setLand(v=>({...v,count_boundary_as_edge:e.target.checked}))}/>Count the study-area boundary as a forest edge</label></div><p>Tree cover is forest for this screening. Maximum two million analysis cells; use a small region first.</p></fieldset>}
        {job.modules.includes("flood")&&<fieldset className="prep-options"><legend>River flood hazard</legend><p>Choose return periods. A 100-year event has a 1% annual exceedance probability under the model assumptions.</p><div className="checkbox-list inline">{[10,100,500].map(p=><label key={p}><input type="checkbox" checked={job.flood.returnPeriods.includes(p)} onChange={()=>patch("flood",{returnPeriods:toggle(job.flood.returnPeriods,p).sort((a,b)=>a-b)})}/>{p}-year</label>)}</div></fieldset>}
        {job.modules.includes("degradation")&&<div className="prep-callout"><strong>Land degradation uses the publisher's fixed periods.</strong><p>2000–2015 baseline and the 2023 assessment. Productivity uses 2001–2015 / 2008–2023; land cover and soil carbon use 2000–2015 / 2015–2022. Years cannot be changed for this published product.</p></div>}
        {job.modules.includes("groundwater")&&<fieldset className="prep-options"><legend>Groundwater periods</legend><div className="prep-periods"><Years title="Groundwater baseline" value={job.groundwater.baseline} min={2003} max={2025} onChange={v=>patch("groundwater",{...job.groundwater,baseline:v})}/><Years title="Groundwater monitoring" value={job.groundwater.monitoring} min={2003} max={2025} onChange={v=>patch("groundwater",{...job.groundwater,monitoring:v})}/></div><p>Only regional daily groundwater data is downloaded. Long periods take time; January 2003 is unavailable. Results describe storage, not well depth. Use a long record for trend interpretation.</p></fieldset>}
        {job.modules.includes("climate")&&<fieldset className="prep-options"><legend>Climate projections</legend><div className="prep-periods"><Years title="Climate baseline" value={job.climate.baseline} min={1950} max={2020} onChange={v=>patch("climate",{...job.climate,baseline:v})}/><Years title="Climate future" value={job.climate.future} min={2021} max={2100} onChange={v=>patch("climate",{...job.climate,future:v})}/></div><p>Prefer 30-year periods for climate comparisons. Short periods are useful for checking the download workflow.</p>
          <fieldset><legend>Models</legend><div className="checkbox-list inline">{MODELS.map(m=><label key={m}><input type="checkbox" checked={job.climate.models.includes(m)} onChange={()=>patch("climate",{...job.climate,models:toggle(job.climate.models,m)})}/>{m}</label>)}</div></fieldset>
          <fieldset><legend>Scenarios</legend><div className="checkbox-list inline">{[["ssp245","SSP2-4.5 · intermediate emissions"],["ssp585","SSP5-8.5 · very high emissions"]].map(([v,label])=><label key={v}><input type="checkbox" checked={job.climate.scenarios.includes(v)} onChange={()=>patch("climate",{...job.climate,scenarios:toggle(job.climate.scenarios,v)})}/>{label}</label>)}</div></fieldset>
          <fieldset><legend>Indices</legend><div className="checkbox-list inline">{(Object.keys(METRICS) as (keyof typeof METRICS)[]).map(m=><label key={m}><input type="checkbox" checked={job.climate.metrics.includes(m)} onChange={()=>patch("climate",{...job.climate,metrics:toggle(job.climate.metrics,m)})}/>{METRICS[m]}</label>)}</div></fieldset>
          <details><summary>Temperature and rainfall thresholds</summary><div className="prep-bounds">{([["hot","Hot days above (°C)"],["warm","Warm nights above (°C)"],["rain","Heavy-rain days at least (mm/day)"],["dry","Dry days below (mm/day)"]] as const).map(([key,label])=><label className="prep-field" key={key}>{label}<input type="number" step="0.1" value={job.climate.thresholds[key]} onChange={e=>patch("climate",{...job.climate,thresholds:{...job.climate.thresholds,[key]:Number(e.target.value)}})}/></label>)}</div></details><p className="prep-callout">About {climateRequests(job).toLocaleString("en")} daily-file subset requests with these selections. Processing may take hours; completed requests are cached.</p>
        </fieldset>}
        {job.modules.includes("drought")&&<fieldset className="prep-options"><legend>Seasonal vegetation health</legend><p>This calculates MODIS VHI, a vegetation-stress screening indicator. It does not reproduce FAO ASIS. Choose growing months appropriate to the study area.</p><div className="prep-periods"><Years title="VHI reference" value={job.drought.reference} min={2001} max={2024} onChange={v=>patch("drought",{...job.drought,reference:v})}/><Years title="VHI comparison" value={job.drought.compare} min={job.drought.reference[0]} max={job.drought.reference[1]} onChange={v=>patch("drought",{...job.drought,compare:v})}/></div>
          <label className="prep-field">Number of growing seasons<select value={job.drought.seasons.length} onChange={e=>patch("drought",{...job.drought,seasons:Number(e.target.value)===1?[job.drought.seasons[0]]:[job.drought.seasons[0],{name:"Season 2",start:11,end:3}]})}><option value={1}>One season</option><option value={2}>Two seasons</option></select></label>
          {job.drought.seasons.map((s,i)=><div key={i} className="prep-season"><label className="prep-field">Season {i+1} name<input value={s.name} maxLength={50} onChange={e=>patch("drought",{...job.drought,seasons:job.drought.seasons.map((v,j)=>j===i?{...v,name:e.target.value}:v)})}/></label>{(["start","end"] as const).map(k=><label className="prep-field" key={k}>{k==="start"?"First month":"Last month"}<select value={s[k]} onChange={e=>patch("drought",{...job.drought,seasons:job.drought.seasons.map((v,j)=>j===i?{...v,[k]:Number(e.target.value)}:v)})}>{months.map((name,m)=><option key={name} value={m+1}>{name}</option>)}</select></label>)}</div>)}<p>Seasons may cross New Year and are labelled by their starting year. They must not overlap. At least 15 reference years must have valid observations.</p>
        </fieldset>}
        {(job.modules.includes("drought")||job.modules.includes("degradation"))&&<label className="prep-field">Area used for statistics<select value={job.landMask} onChange={e=>patch("landMask",e.target.value as Job["landMask"])}><option value="worldcover2021">WorldCover 2021 · crop area for VHI, non-water area for degradation</option><option value="all-land">Entire boundary · no crop or water mask</option></select><small>The fixed 2021 map does not establish historical cropping. Full-boundary mode must not be read as crop-only or land-only statistics.</small></label>}</div>;}
